#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_READLINE_READLINE_H 1
#define HAVE_READLINE_HISTORY_H 1
#define HAVE_RL_DEPREP_TERM_FUNCTION 1
#define HAVE_RL_COMPLETION_APPEND_CHARACTER 1
#define HAVE_RL_BASIC_WORD_BREAK_CHARACTERS 1
#define HAVE_RL_COMPLETER_WORD_BREAK_CHARACTERS 1
#define HAVE_RL_COMPLETER_QUOTE_CHARACTERS 1
#define HAVE_RL_ATTEMPTED_COMPLETION_OVER 1
#define HAVE_RL_LIBRARY_VERSION 1
#define HAVE_RL_CLEANUP_AFTER_SIGNAL 1
#define HAVE_REPLACE_HISTORY_ENTRY 1
#define HAVE_REMOVE_HISTORY 1
#endif
