#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_ARPA_INET_H 1
#define ENABLE_IPV6 1
#define INET6 1
#define HAVE_STRUCT_SOCKADDR_IN_SIN_LEN 1
#define HAVE_SIN_LEN 1
#define HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1
#define HAVE_SOCKADDR_STORAGE 1
#define HAVE_STRUCT_SOCKADDR_SA_LEN 1
#define HAVE_SA_LEN  1
#define HAVE_NETINET_TCP_H 1
#define HAVE_NETINET_UDP_H 1
#define HAVE_SENDMSG 1
#define HAVE_RECVMSG 1
#define HAVE_STRUCT_MSGHDR_MSG_CONTROL 1
#define HAVE_ST_MSG_CONTROL 1
#define HAVE_GETNAMEINFO 1
#define HAVE_GETADDRINFO 1
#define HAVE_TYPE_SOCKLEN_T 1
#define HAVE_SYS_UN_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SOCKET 1
#define HAVE_GETIPNODEBYNAME 1
#define HAVE_SOCKETPAIR 1
#define HAVE_GETHOSTNAME 1
#endif
